### PR TITLE
Adding support for ie8

### PR DESCRIPTION
**Pull request by lafritay**
1. ie8 doesn't fire the onload event
2. ie8 doesn't reliably call object.load unless the attribute
is set before it.

For more details, see: http://stackoverflow.com/questions/7438990/jquery-callback-on-image-load-when-changing-the-src

### CODE REVIEW

**Comment by lafritay** [comment]
Also, I'm a tad new to javascript and wasn't sure of the best way to detect an old browser purely with javascript.  I'm certainly open to other approaches to determining the browser version.

**Comment by mrchimp** [comment]
Generally you should detect which browser *features* are available (e.g. the onload event) and use whatever is available, rather than detecting and coding for specific browsers or browser versions.

**Comment by lafritay** [comment]
Unfortunately, I've got the same problem. I'm going to be on vacation the week of 8/3 and traveling for work the week of 8/10. I could meet on 8/8 or 8/9 but that is about it...

-----Original Message-----

**Comment by mrchimp** [comment]
...wait, what?

**Comment by lafritay** [comment]
Ha, apologies, it appears I replied to the wrong thread... That's embarrassing...

-----Original Message-----

**Comment by rejas** [comment]
I agree with @mrchimp. Suppor-For-IE8 I would only merge if it is coded a little more flexible. I wouldnt want the code to become more "specialized" like that for such an outdated browser. Maybe you can rewrite your code to use a mechanism like it is already in there for css-transitions?

**Comment by lafritay** [comment]
Yep, makes total sense.  Any chance you could point me to the code you're referencing for the css-transitions?  I don't know my way around this codebase very well yet.

**Comment by rejas** [comment]
I'm travelling at the moment, so the only advice I can give you is to look at the SRC JavaScript file for the variable cssTransitionSupport, how it is set and used. More help in two weeks..

**Comment by rejas** [comment]
Closing due to inactivity (and due to IE8 not being being supported anymore)

**Pull request closed without merging**
