### PR TITLE
These edits make imagelightbox compatible with webpack out of the box

### PR DESCRIPTION
**Pull request by paxperscientiam**

### CODE REVIEW

**Comment by paxperscientiam** [comment]
don't merge just yet

**Comment by rejas** [comment]
I do. Currently using this line:
import 'imagelightbox/src/imagelightbox';

Will merge it into develop and see how it works out :-)

**Comment by rejas** [comment]
Works like a charm! Thanks a lot. Any idea if there is an equivalent for the styles?

**Comment by paxperscientiam** [comment]
Great! I think so, though I will have to dig. I'll open an issue to remind me.

**Pull request closed without merging**
