### PR TITLE
Here is the code we talked about earlier.

### PR DESCRIPTION
**Pull request by paxperscientiam**
This code has all the features, but I have to say that I am an amateur when it comes to coding in javascript. The harshest criticism imaginable is most welcome :)

### CODE REVIEW

**Comment by paxperscientiam** [comment]
Usage example:

```javascript
 light.box(['a[data-imagelightbox="z"]',{
                                        activity:true,
                                        arrows:true,
                                        navigation:true,
                                        overlay:true,
                                        caption:true,
                                        button:true
                                    }
                                              ]);
```

**Comment by rejas** [comment]
I like the idea of having options for configuring the imagelightbox, but I would but those into an "options"-object so you dont have to pass those "activity, arrows etc" values in the correct order (and that would later be helpful if we want to add data-options-attributes)
Also could you move your code into the main js file isntead of adding a new file (and remove the code from the demo.html)?

**Comment by paxperscientiam** [comment]
Sure thing @rejas

**Comment by paxperscientiam** [comment]
Hey @rejas PR implements your UI features now, but I'm having some trouble with the 'navigation' element. Suggestions?

**Comment by rejas** [comment]
Thanks for the PR; I created a new branch "refactor_options" and merged it into that one (instead of master). will look into the navigation-element, everything else seems to work atm. nice and thx again

**Comment by paxperscientiam** [comment]
You're welcome!

**Comment by rejas** [comment]
So, I also fixed the navigation stuff, merged it into master, updated the docs and demo a little. Care to take a look to see if I missed something? Would be really appreciated :-)

**Comment by paxperscientiam** [comment]
Hi there @rejas , sorry about the disappearance. It looks like everything is working well! I have some other thoughts, but I'll post it as an issue. Nice work, man!

**Pull request closed without merging**
