### PR TITLE
Video

### PR DESCRIPTION
**Pull request by GenaBitu**
Hi, I started some preliminary work on getting video to work in imagelightbox. It doesn't work yet, but I thought I'd let you know about it and maybe you would have some better insight into how this could be made to work...

### CODE REVIEW

**Comment by GenaBitu** [comment]
Hey, I got it working (at least a minimal example...). It's used like:

```html
<a data-imagelightbox="a" data-ilb2-video="{\"src\":\"\video.mp4", \"controls\":\"controls\"}"><img src="thumbnail.jpg"></a>
```
Basically, you just include a `data-ilb2-video` attribute with JSON options which will be applied as attributes to a video tag (https://www.w3schools.com/tags/tag_video.asp)

Going forward, I would like to maybe add support for multiple sources as per https://stackoverflow.com/questions/39179834/difference-between-video-src-video-and-video-source-source-vide.

What do you think?

**Comment by GenaBitu** [comment]
I've added support for multiple sources, so the usage is now like

```html
<a data-imagelightbox="a" data-ilb2-video="{\"controls\":\"controls\", \"sources\":[{\"src\":\"video.mp4\", \"type\":\"video/mp4\"}]}"><img src="thumbnail.jpg"></a>
```

The sources field is an array of sources (also applied as attributes to the `source` element).
Of course, the simpler way with just a `src` attribute still works

**Comment by GenaBitu** [comment]
Line 406 is causing some spurious requests to `https://mywebpage.com/undefined` - I don't yet understand why.

**Comment by rejas** [comment]
Great inititative, goodf work so far.
Nitpicking: 
a) could you add an example to the doc page so we can see the progress? 
b) this data-attribute looks so clunky, no way anyone will get it right the first time implementing it:
`data-ilb2-video="{\"controls\":\"controls\", \"sources\":[{\"src\":\"video.mp4\", \"type\":\"video/mp4\"}]}`
isnt there a better syntax way for this? maybe splitting up the attributes?

**Comment by GenaBitu** [comment]
a) Definitely
b) Yeah, maybe write it as 

```html
<a data-imagelightbox="a" data-ilb2-video='{"controls":"controls", "sources":[{"src":"video.mp4", "type":"video/mp4"}]}'><img src="thumbnail.jpg"></a>
```
Then It's just a JSON...
About splitting it: There are 9 fields just for the `<video>` tag. But maybe the sources could be split to their own field...

**Comment by GenaBitu** [comment]
Hey, I've fixed the problem with the spurious requests and the alignment of the video. The video jitters on load though. I have no idea how to fix that...
I've also added a demo example.

**Comment by rejas** [comment]
Awesome! Now only missing is documentaton below the example and in the README. Then its ready to merge or what do you think?

**Comment by GenaBitu** [comment]
Done. I think it's ready to merge, because I see no way of removing the jitter on scrolling to a video.

**Pull request merged**
