### PR TITLE
History api integration

### PR DESCRIPTION
**Pull request by paxperscientiam**
Progress thus far:

- [x] History state changes on image load.
- [x] `window.location.pathname` updates with each image load with the following form: #!imagelightbox/<data-imagelightbox value>/<target number>
- [x] alterations to `window.location.pathname` are removed on quit.
- [ ] a function to handle image loading on browser "back" and "forward" and "refresh". (partially there)

EDIT

- [x] will load image in history object on refresh.

Because of the complexity and care it would take to integrate History properly, I would appreciate your input @rejas before progressing further.

Happy holidays.

### CODE REVIEW

**Comment by rejas** [comment]
I am a little under the weather right now to read code so just this one thing: don't see any tests in the commit, why not add some (in case you are bored ;-) 
will be back in fullforce in 2017. happy new year!

**Comment by paxperscientiam** [comment]
Take a good rest and hopefully you are well now that it is 2017!

Test added :)

**Comment by paxperscientiam** [comment]
@rejas fixed the current conflict if you'd like to test.

**Comment by rejas** [comment]
I tested it, looks nice on first sight. Further testing will occur :-)

But I dont see any nightwatch js tests for the feature in your code?

Also, quitOnDocClick doesnt work anymore, could you look into it?

**Comment by paxperscientiam** [comment]
@rejas Ah, I see what I did. I had removed the `$(document).ready(...)` wrapper during a test, though forgot to replace it. Fixed, I believe.

**Comment by rejas** [comment]
Thx for the fix.
Regarding nightwatch/selenium: 
Yeah, it is not the most glorious task but it should be done :-( First of one would need to formulate for himself (no code :-) what should be tested, for example here the usecase would be: 
- open imagelightbox, navigate to next slide, make sure that the url changed.  
- open imageligthbox with history-url, make sure that the correct image is displayed
You can take the existing tests as a blueprint for how the code works (I am not a pro in that field neither :-). If you need help , shout :-)

**Comment by rejas** [comment]
Closed via https://github.com/rejas/imagelightbox/pull/149 
Thx for your work, helped the other PR.

**Pull request closed without merging**
