### PR TITLE
Tweak animations

### PR DESCRIPTION
**Pull request by paxperscientiam**
I have tweaked 'entry' and 'exit' animation for click events. I felt the current transition is way to jarring. 

What you say?

EDIT: hold off, needs bit more tweaking

EDIT2:
Hi @rejas ,

I've tweaked navelement activation animation so not so jarring. Converted image slide-in/out to use a 'ease-in' instead of 'linear'. Also changed the default animation speed so it's not so quick.

### CODE REVIEW

**Comment by GenaBitu** [comment]
Hi, I merged the current `develop` into this PR and pushed it to this repo. I'll try the tweaks.

**Comment by GenaBitu** [comment]
Ok, my thoughts (and this is quite subjective):
- I like the navigation tweak
- I like the easing animation
- I strongly dislike making the animation "wider" - for vertical photos like in the docs, it's too much movement
- I dislike making the animation slower (this goes hand-in-hand with the previous point): if we were to leave the width as it is now, then 350 is painfully slow.

**Comment by paxperscientiam** [comment]
Thank you. Very helpful

**Comment by GenaBitu** [comment]
Hmm, GitHub marked this PR as merged when I merged #179 - not my intention.

**Comment by rejas** [comment]
Probably because you based your PR on this one, I'd guess...

**Pull request merged**
