### PR TITLE
Major changes

### PR DESCRIPTION
**Pull request by paxperscientiam**
Hi @rejas 

I've implemented much of the refactoring I spoke of. There is still much to do.

I also partially implemented namespacing and pushState.

This PR isn't ready for acceptance, but I'd like your two cents on the direction of my changes. Also, if you spot any bugs (i'm sure there are plenty), please do let me know.

I'll keep moving forward with it in the mean time.

### CODE REVIEW

**Comment by rejas** [comment]
Thx, will take a look at it tomorrow. Could you maybe rebase it to the v0.5.0 I just released? And keep the intendation (4 instead of 2 spaces) so it makes it easier to read the diff :-)

**Comment by paxperscientiam** [comment]
Noob question, but how do I "rebase it to the v0.5.0"? I'll change the tabbing :P

**Comment by rejas** [comment]
You should also see like me here in this thread a message from git, telling you that the branch has conflicts. Just follow the instructions given there (basically you merge my master into the branch of yours again)

**Comment by paxperscientiam** [comment]
@rejas I think I did it.

**Comment by rejas** [comment]
Sorry, I tried to look at it, but the changes are way to big to make a valid statement when they are presented in this big chunk of pull request. 
Some thoughts I could make out:
- where are the csstransition checks gone?
- what is that pro var at the bottom?
- disableBackgroundMovement ? 
- where is the change that you mentioned in https://github.com/rejas/imagelightbox/issues/35 ?

I will gitcheckout your branch and take a look at it on my machine, but for future reference, please try to split your patches (even if they are only for review) into smaller sizes. That way we can easilier review, test, fix, comment etc pp.

**Comment by paxperscientiam** [comment]
Hey @rejas , sorry, you make a good point. If you wanna close this up. I will do just as you suggest and break up things into smaller patches.

**Pull request closed without merging**
