### PR TITLE
Travis fix

### PR DESCRIPTION
**Pull request by GenaBitu**
I've tried to fix the Travis builds:
- Multi-platform nightwatch configuration
- Fixed gulp so that nightwatch actually exits after finishing
- Using headless chromium

Unfortunately it still doesn't work. `gulp test` works fine for me locally (Linux) and I have no idea what the error message in Travis means. Any ideas?

### CODE REVIEW

**Comment by rejas** [comment]
hi @GenaBitu sorry for the delay in answering. As for your work: Dont know why that still thrwos error. But to be honest: I am not very satisfied with (gulp-)nightwatch. Maybe you know some other easy to implement test-solution for those few test cases we have?

**Comment by GenaBitu** [comment]
Don't worry... I have absolutely no idea, I didn't even know that you could do something like this before looking into this issue.

**Comment by GenaBitu** [comment]
I've recently read the [2018 State of JS](https://2018.stateofjs.com/) and it seems most people are using Jest and (probably more importantly) are very happy with it...

I've never used it (or any other JS testing tool)...

**Comment by rejas** [comment]
Jest is more for unit testing, if I see it correctly (or for React tests)...

**Comment by rejas** [comment]
Fixed testing with https://github.com/rejas/imagelightbox/pull/189

**Pull request closed without merging**
