### PR TITLE
Caption simplify

### PR DESCRIPTION
**Pull request by paxperscientiam**
Just a bit of refactoring/simplifying.

### CODE REVIEW

**Comment by paxperscientiam** [comment]
Hi @rejas . Im not sure what to do about this "dist" conflict.

**Comment by rejas** [comment]
I'd just delete the file in dist and run the normal gulp build process :-)

**Comment by paxperscientiam** [comment]
This is no longer necessary (covered by PR #84). Agreed?

**Comment by rejas** [comment]
agreed, will close this in favor of #84

**Pull request closed without merging**
