### PR TITLE
Client percentage positioning

### PR DESCRIPTION
**Pull request by paxperscientiam**
@rejas 

* This PR switches height calculations to jQuery based.
* fixed caption height bug
* introduces vertical gutter option, replacing internal image display height calculation as function of this option
* introduces vertical offset as function of gutter

### CODE REVIEW

**Comment by paxperscientiam** [comment]
@rejas fixed! I forgot to fetch newest changes (derp)

**Comment by paxperscientiam** [comment]
@rejas Any issues with this?

**Comment by rejas** [comment]
only doc updates mssing, then I'll merge it :-)

**Comment by paxperscientiam** [comment]
@rejas Should be golden

**Comment by paxperscientiam** [comment]
@rejas Something missing?

**Comment by rejas** [comment]
Sorry for the delay, merged into develop

**Comment by paxperscientiam** [comment]
Yay!

**Pull request merged**
