### PR TITLE
Fix for caption flashing and added secondary caption source

### PR DESCRIPTION
**Pull request by paxperscientiam**
@rejas 

I did away with caption flashing. Now, the default is the caption box is empty if the user does not add caption text to any of the images.

As well, I created a new data attribute -- "data-imagelightbox-caption" that can be added to links in the cases where the user does not want/need a thumbnail.

### CODE REVIEW

**Comment by rejas** [comment]
Good idea with the data-attribute, but again this PR has so much old changes in it, itmakes me wonder how you manage your branches at your repository? did you start from my latest master?

**Comment by paxperscientiam** [comment]
From the commandline now -- never figured out SourceTree. I will rebase (?).

**Comment by paxperscientiam** [comment]
Hey @rejas. OK, I scrapped it and re-added the changes based off the current upstream/master.

As for indentation, I think I have it now. If not, can you point out where I'm failing? I'm using emacs and just realized I was using a conflicting indentation mode. Turned it off, so it should at least be better now.

**Comment by rejas** [comment]
I have no idea about emacs, but thats why I added the ".editorconfig" file to the project that gives the editor hints on how to treat sutff like space etc. IntelliJ supports it and a quick google search found https://github.com/editorconfig/editorconfig-emacs. Will probably adda jshint/eslint gulp task soon so that when building the project one gets notified if the style is incorrect...

**Pull request closed without merging**
