### PR TITLE
Dynamically adding

### PR DESCRIPTION
**Pull request by Salon-sai**
The document was written in fix_add.md. As Chinese student, My English is not proficient and I hope it will give your some practice suggestion to make the plugin well.

### CODE REVIEW

**Comment by rejas** [comment]
Thank you once again, I commented in the files directly.

**Comment by rejas** [comment]
Tahnks for the info, but could you modify your pull request to not have the chinese in it? 
Also, do oyu have the time to add an example of the dynamically adding feature to the demo page?

**Comment by Salon-sai** [comment]
I have added an example of the dynamically adding feature and remove the Chinese in it.

**Comment by rejas** [comment]
thanks for your work!

**Pull request merged**
