### PR TITLE
fix ios vertical positioning issue

### PR DESCRIPTION
**Pull request by hanwiz**
This also fixes the navigation arrow location in mobile.

### CODE REVIEW

**Comment by rejas** [comment]
a) still want to reproduce the bug so please specify where it appears (which ios / hardware / BBrwoser version)
b) what is the problem with navigation buttons in mobil? 
screenshots would be really nice to demosntrate. thx in advance (and also for the pull request)

**Comment by hanwiz** [comment]
ios-compare

This is the current behavior. You can see vertical position is off in iOS simulator, which I can also see my iPad2 iOS8 Safari. Also, navigation bar in the desktop chrome is off the center. 

My code fix the both case.

**Comment by hanwiz** [comment]
iosfix-after

This is from my local demo after fix is applied.

**Comment by hanwiz** [comment]
iosfix-after

This is my local demo after fix.

**Comment by hanwiz** [comment]
iosfix

This is my local demo after fix.

**Comment by rejas** [comment]
thx :-)

**Pull request merged**
