### PR TITLE
History patch

### PR DESCRIPTION
**Pull request by paxperscientiam**
Hi @rejas 

As promised, I have gone back to the drawing board; I will now be introducing augmentations in more manageable form.

What does this code do?
• When ImageLightbox is instantiated, a history entry is pushed. Going to the previous or next image pushes a history entry. Associated with these history pushes is an augmented URL and augmented page title, both reflecting the state of the app.

Pressing the back button of the browser takes the user to the previously invoked lightbox object; the opposite is true when the forward button is pressed.

### CODE REVIEW

**Comment by rejas** [comment]
Cool idea, didnt notice that in your big patch before :-) Although again your intendation (6 spaces now instead of 4) makes the diff again hard to read :-( Maybe update the PR once again with correct 4? (I really do feel bad for asking you so much since you work so much for this project :-(
And one more question: What git program do you use for managin your repository and preparing the pullrequests? Just out of curiosity what other people are using...

**Comment by paxperscientiam** [comment]
Yeah, my indentation settings in .emacs were botched. Fixed it! Hey, it's no problem; I'm just happy to be involved. It's a great opportunity to improve my javascript skills :)

You'll think this is silly, but I don't use any git program. I tried using git commandline program, but it just gave me a headache. So did github's desktop program. So, I've just been copy-pasting into Github :/

What do you use?

**Comment by rejas** [comment]
I am using Sourcetree from Atlassian since I am running either Windows or MacOs. Since you mentioned emacs you might be running Linux which isnt suported :-( Having a GUI for the branches and handling remote branches makes git a lot easier for me. Commandline I only use when something is broken beyond sourcetrees repair :-)
Now I have your history branch locally and can take alook at it, please be patient though, my DSL line is broken so I can only sometimes get internet access. Stay tuned :-)

**Comment by rejas** [comment]
Damn, 5 minutes looking at your code and I found one in mine :-D see https://github.com/rejas/imagelightbox/issues/42 Will fix that first. As a first review comment though: Add an example to the demo page so we can test the history stuff more easily :-)

**Comment by paxperscientiam** [comment]
Still working on this.

**Comment by rejas** [comment]
Good morning, to better test your history patch I merged into a new branch on my repository and did some cleanups. Still a lot of stuff to do I say. While the history gets expanded, the back button doesnt work, I get a "TypeError: imgPath is undefined" in firefox. And when it works, somehow multiple copies of the same imagelightbox-dom-element are added, see screenshot
screen shot 2016-08-06 at 11 41 22 am

**Comment by paxperscientiam** [comment]
"resetting" things on my end. Will try again.

**Pull request closed without merging**
